<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-07-18 at 12:51:08.
 */
class TagCloudUtilsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TagCloudUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TagCloudUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TagCloudUtils::simpleTagCloud
     * @todo   Implement testSimpleTagCloud().
     */
    public function testSimpleTagCloud() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
