<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-07-18 at 12:51:03.
 */
class EntrytypeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Entrytype
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Entrytype;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
