<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-08-15 at 11:18:11.
 */
class CreateConceptQueryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CreateConceptQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreateConceptQuery();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CreateConceptQuery::getResult
     * @todo   Implement testGetResult().
     */
    public function testGetResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
